### ISSUE TITLE
Unable to set ingress path other than /

### ISSUE THREAD

**Issue by manali14** [pact-foundation/pact-broker-chart#70]
In ingress there is no way to set any other Prefix other than /, so its difficult to configure pact to a custom path.

Details here: https://github.com/pact-foundation/pact-broker-chart/blob/master/charts/pact-broker/templates/ingress.yaml#L33

In order to get it working, I have to disable ingress from helm chart and create it separately because my pact server is running on a custom path i.e, /pact

**Comment by ChrisJBurns** [comment]
Hi @manali14 

Just looking at this now, would the addition of a `pathPrefix` value be suffice? An example:
```yaml
       paths:
          - path: {{ Values.ingress.path }}
            pathType: Prefix
```

Where `ingress.path` is defaulted to `/` for backwards compatibility. You should then be able to use it by passing in `ingress.path: "/pact"`
